### ISSUE TITLE
The `zeroes` and `zero` interface does not seem fully implemented.

### ISSUE THREAD

**Issue by Krastanov** [wbhart/AbstractAlgebra.jl#22]
I tried the following code:

```
using AbstractAlgebra
R, (e,) = PolynomialRing(RealField, ["e"])
zero(e) # works as expected
R(0) # works as expected
zeros(typeof(e),4) # fails, while I expected it will return [R(0), R(0), R(0), R(0),]
zero(typeof(e)) # fails, while I expected it will return R(0)
```

Is this indeed functionality that is not implemented yet, or is there a specific reason this should not be implemented?

**Comment by wbhart** [comment]
This is not the official AbstractAlgebra repo. See https://github.com/Nemocas/AbstractAlgebra.jl/

One cannot construct objects from their type alone. See:

https://nemocas.github.io/AbstractAlgebra.jl/latest/types/

**Comment by Krastanov** [comment]
oops... my bad!
Thanks for the pointers.
